import { useEffect, useState } from 'react'

const resumePath = '/assets/Ritik_Dandir_Resume.pdf'
const photoPath = '/assets/ritik-resume-photo.png'
const navItems = [['home', 'Home'], ['about', 'About'], ['experience', 'Experience'], ['expertise', 'Expertise'], ['tools', 'Tools'], ['education', 'Education'], ['contact', 'Contact']]
const responsibilities = [
  'Prepare techno-commercial offers and engineering cost estimates based on project requirements, technical specifications, and defined scope.',
  'Support BIW welding process-related engineering activities and evaluation of manufacturing requirements.',
  'Perform engineering and manufacturing process analysis to identify opportunities for process optimization and improved manufacturing efficiency.',
  'Support cycle-time analysis and optimization activities for manufacturing processes.',
  'Perform fixture costing and estimation activities, including evaluation of engineering requirements and associated costs.',
  'Prepare and maintain engineering and business documentation for project and management requirements.',
  'Develop business dashboards and analytical reports using MS Excel and available tools.',
  'Coordinate technical information from relevant stakeholders for preparation of commercial and engineering proposals.',
  'Analyse engineering requirements and associated cost elements to support commercial decision-making and project estimation.',
  'Prepare technical information and presentations for communication of engineering and commercial requirements.',
]
const expertise = [
  ['01', 'BIW Welding Process', 'Manufacturing process knowledge for body-in-white welding environments.'], ['02', 'Fixture Costing & Estimation', 'Engineering requirement evaluation and associated cost estimation.'], ['03', 'Techno-Commercial Estimation', 'Structured offers aligned with scope, specifications and requirements.'], ['04', 'Manufacturing Process Analysis', 'Practical analysis focused on efficient manufacturing.'], ['05', 'Process Optimization', 'Identifying opportunities to improve manufacturing efficiency.'], ['06', 'Cycle-Time Optimization', 'Supporting cycle-time analysis across manufacturing processes.'], ['07', 'Engineering Cost Analysis', 'Breaking down engineering cost elements for decisions.'], ['08', 'Engineering Documentation', 'Clear project, management and proposal documentation.'], ['09', 'Technical Proposal Preparation', 'Communicating technical and commercial requirements.'], ['10', 'Business & Engineering Reporting', 'Dashboards and analytical reports for stakeholders.'], ['11', 'Excel-Based Analysis', 'Advanced Excel used for engineering and business analysis.'], ['12', 'Dashboard Development', 'Business dashboards built from available tools and data.'],
]
const tools = [['MS Excel', 'Advanced', 'Engineering analysis, estimation and reporting'], ['MS PowerPoint', '', 'Technical information and presentations'], ['On-shape CAD', 'Intermediate', 'CAD support for engineering communication'], ['AutoCAD', 'Basic', 'Engineering drawing support'], ['Catia', 'Basic', 'Foundational CAD capability']]
const professionalSkills = ['Analytical Thinking', 'Problem Solving', 'Technical Communication', 'Team Collaboration', 'Documentation Management', 'Time Management', 'Engineering Coordination', 'Business Communication']
const education = [['2024', 'Precision Engineering Certificate Course', 'SSR Global Skill Park, Bhopal'], ['2023', 'Bachelor of Technology (B.Tech) - Mechanical Engineering', 'Chameli Devi Group of Institutions, Indore'], ['2019', 'Class XII - PCM', 'Shree Vaishnav Vidya Mandir, Khargone'], ['2016', 'Class X', 'Shree Vaishnav Vidya Mandir, Khargone']]

function Arrow() { return <span aria-hidden="true" className="arrow">↗</span> }
function SectionLabel({ number, children }) { return <div className="section-label reveal"><span>{number}</span>{children}</div> }
function DownloadButton({ className = '' }) { return <a className={`button button-primary ${className}`} href={resumePath} download="Ritik_Dandir_Resume.pdf"><span>↓</span> Download Resume</a> }
function Navbar({ menuOpen, setMenuOpen, active, scrolled }) { return <header className={`navbar ${scrolled ? 'scrolled' : ''}`}><a href="#home" className="brand" onClick={() => setMenuOpen(false)}><span className="brand-mark">RD</span><span>RITIK <b>DANDIR</b></span></a><button className="menu-toggle" aria-label="Toggle navigation" aria-expanded={menuOpen} onClick={() => setMenuOpen(!menuOpen)}><span /><span /><span /></button><nav className={menuOpen ? 'nav-links open' : 'nav-links'}>{navItems.map(([id, label]) => <a key={id} className={active === id ? 'active' : ''} href={`#${id}`} onClick={() => setMenuOpen(false)}>{label}</a>)}<DownloadButton /></nav></header> }

function Hero() { return <section id="home" className="hero section-shell"><div className="hero-grid" aria-hidden="true"><span /><span /><span /><span /></div><div className="hero-photo-wrap reveal reveal-photo"><div className="photo-frame"><img src={photoPath} alt="Ritik Dandir, Mechanical Engineer" /></div><div className="photo-caption"><i /> Engineering · Automotive · Precision</div></div><div className="hero-copy"><div className="eyebrow reveal reveal-1">EXECUTIVE ENGINEER <b>•</b> JBM GROUP <span>GURUGRAM</span></div><h1 className="reveal reveal-2">RITIK <em>DANDIR</em></h1><p className="hero-role reveal reveal-3">Mechanical Engineer</p><p className="hero-specialty reveal reveal-4">BIW <i>/</i> FIXTURE COSTING <i>/</i> MANUFACTURING ENGINEERING <i>/</i> TECHNO-COMMERCIAL ESTIMATION</p><p className="hero-summary reveal reveal-5">Building efficient manufacturing solutions through engineering, analysis &amp; innovation.</p><div className="hero-actions reveal reveal-6"><DownloadButton /><a className="button button-outline" href="#contact">Let's connect <Arrow /></a></div><div className="hero-tags reveal reveal-6"><span>BIW WELDING</span><span>FIXTURE COSTING</span><span>PROCESS OPTIMIZATION</span></div></div><div className="hero-code" aria-hidden="true">ME / 01<br /><span>23°12′N · 77°25′E</span></div><a className="scroll-cue" href="#about"><span>SCROLL TO EXPLORE</span><i /></a></section> }

function About() { return <section id="about" className="section section-light"><div className="section-shell"><SectionLabel number="01 /">About Me</SectionLabel><div className="about-grid"><div className="reveal"><h2>Engineering clarity.<br /><em>Manufacturing focus.</em></h2><div className="draw-line" /></div><div className="about-copy reveal reveal-2"><p>Mechanical Engineering professional with experience in automotive manufacturing engineering, BIW welding processes, fixture costing, techno-commercial estimation, process analysis, cycle-time optimization, and engineering documentation.</p><p>Currently working as an Executive Engineer at JBM Group. Experienced in preparing engineering cost estimates and techno-commercial offers, supporting fixture costing activities, analyzing manufacturing processes, developing business dashboards, and coordinating technical information for engineering and commercial proposals.</p><p>Strong interest in manufacturing engineering, fixture/tooling, process optimization, engineering costing, and project engineering within the automotive industry.</p></div></div><div className="stat-strip reveal"><div><strong>2024</strong><span>CURRENT ROLE</span></div><div><strong>JBM</strong><span>GROUP</span></div><div><strong>BIW</strong><span>ENGINEERING FOCUS</span></div><div><strong>12</strong><span>CORE CAPABILITIES</span></div></div></div></section> }

function Experience() { return <section id="experience" className="section section-navy"><div className="section-shell"><SectionLabel number="02 /">Professional Experience</SectionLabel><div className="experience-layout"><div className="experience-aside reveal"><div className="timeline-marker">01</div><div><p className="company">JBM GROUP</p><p className="location">Gurugram</p></div></div><div className="experience-main"><div className="timeline-rail" /><div className="role-row reveal"><div><h3>Executive Engineer <span>- Engineering</span></h3><p className="date">2024 - Present</p></div><span className="role-tag">CURRENT ROLE</span></div><ul className="responsibilities">{responsibilities.map((item, i) => <li className="reveal" style={{ '--i': i }} key={item}>{item}</li>)}</ul></div></div></div></section> }

function Expertise() { return <section id="expertise" className="section section-light blueprint"><div className="section-shell"><SectionLabel number="03 /">Engineering Expertise</SectionLabel><div className="section-intro reveal"><h2>Precision in every<br /><em>engineering detail.</em></h2><p>Core capabilities spanning automotive manufacturing, estimation, analysis and technical communication.</p></div><div className="expertise-grid">{expertise.map(([number, title, desc], index) => <article className="expertise-card reveal" style={{ '--i': index }} key={title}><span className="card-index">{number}</span><div className="card-icon">+</div><div><h3>{title}</h3><p>{desc}</p></div><Arrow /></article>)}</div></div></section> }

function Tools() { return <section id="tools" className="section section-blue"><div className="section-shell"><SectionLabel number="04 /">Tools &amp; Technologies</SectionLabel><div className="tools-layout"><div className="reveal"><h2>Tools that turn<br /><em>data into decisions.</em></h2><p className="muted-light">A practical working toolkit for engineering analysis, documentation, reporting and commercial proposals.</p></div><div className="tools-grid">{tools.map(([name, level, detail], index) => <div className="tool-card reveal" style={{ '--i': index }} key={name}><div className="tool-top"><h3>{name}</h3>{level && <span>{level}</span>}</div><p>{detail}</p><div className="tool-mark">↗</div></div>)}</div></div><div className="skills-row reveal"><div><p className="mini-heading">PROFESSIONAL SKILLS</p><div className="skill-pills">{professionalSkills.map(skill => <span key={skill}>{skill}</span>)}</div></div></div></div></section> }

function Education() { return <section id="education" className="section section-light"><div className="section-shell"><SectionLabel number="05 /">Education</SectionLabel><div className="education-intro reveal"><h2>Built on a foundation<br /><em>of precision.</em></h2><p>Education and continuous technical development supporting a career in manufacturing engineering.</p></div><div className="education-timeline">{education.map(([year, title, school], index) => <article className="reveal" style={{ '--i': index }} key={year}><span className="edu-year">{year}</span><span className="edu-node" /><div><h3>{title}</h3><p>{school}</p></div></article>)}</div></div></section> }

function Contact() { return <section id="contact" className="contact-section"><div className="section-shell"><SectionLabel number="06 /">Contact</SectionLabel><div className="contact-grid"><div className="reveal"><p className="contact-kicker">OPEN TO ENGINEERING CONVERSATIONS</p><h2>Let's connect.</h2><div className="draw-line light" /><p>Interested in discussing manufacturing engineering, fixture engineering, costing, technical proposals, or collaboration?</p><div className="contact-actions"><a className="button button-light" href="mailto:ritikdandir@gmail.com">Email Me <Arrow /></a><a className="button button-ghost" href="https://www.linkedin.com/in/ritikdandir" target="_blank" rel="noreferrer">LinkedIn <Arrow /></a><DownloadButton className="button-ghost" /></div></div><div className="contact-details reveal reveal-2"><a href="tel:+917974268544"><span className="contact-symbol">T</span><span>+91 797-426-8544</span></a><a href="mailto:ritikdandir@gmail.com"><span className="contact-symbol">@</span><span>ritikdandir@gmail.com</span></a><span><span className="contact-symbol">⌖</span><span>Khargone, Madhya Pradesh, India</span></span></div></div></div></section> }
function Footer() { return <footer><div className="section-shell footer-inner"><div><strong>RITIK <span>DANDIR</span></strong><p>Mechanical Engineer · BIW · Fixture Costing · Estimation</p></div><p>© 2026 Ritik Dandir</p></div></footer> }

export default function App() {
  const [menuOpen, setMenuOpen] = useState(false); const [active, setActive] = useState('home'); const [scrolled, setScrolled] = useState(false); const [progress, setProgress] = useState(0)
  useEffect(() => { const onScroll = () => { const max = document.documentElement.scrollHeight - window.innerHeight; setScrolled(window.scrollY > 40); setProgress(max ? (window.scrollY / max) * 100 : 0) }; onScroll(); window.addEventListener('scroll', onScroll, { passive: true }); const sectionObserver = new IntersectionObserver(entries => entries.forEach(entry => { if (entry.isIntersecting) setActive(entry.target.id) }), { rootMargin: '-35% 0px -55% 0px' }); navItems.forEach(([id]) => { const el = document.getElementById(id); if (el) sectionObserver.observe(el) }); const revealObserver = new IntersectionObserver(entries => entries.forEach(entry => { if (entry.isIntersecting) { entry.target.classList.add('is-visible'); revealObserver.unobserve(entry.target) } }), { threshold: 0.12 }); document.querySelectorAll('.reveal').forEach(el => revealObserver.observe(el)); const onPointer = event => { document.documentElement.style.setProperty('--mx', `${(event.clientX / window.innerWidth - .5) * 2}`); document.documentElement.style.setProperty('--my', `${(event.clientY / window.innerHeight - .5) * 2}`) }; window.addEventListener('pointermove', onPointer, { passive: true }); return () => { window.removeEventListener('scroll', onScroll); window.removeEventListener('pointermove', onPointer); sectionObserver.disconnect(); revealObserver.disconnect() } }, [])
  return <><div className="progress-bar" style={{ width: `${progress}%` }} /><Navbar menuOpen={menuOpen} setMenuOpen={setMenuOpen} active={active} scrolled={scrolled} /><main><Hero /><About /><Experience /><Expertise /><Tools /><Education /><Contact /></main><Footer /><button className="to-top" aria-label="Scroll to top" onClick={() => window.scrollTo({ top: 0, behavior: 'smooth' })}>↑</button></>
}
